version = 0.1

[default]
[default.global.parameters]
stack_name = "dev-ecommerce-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "dev-ecommerce-stack"
region = "us-east-1"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[staging]
[staging.global.parameters]
stack_name = "staging-ecommerce-stack"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ecommerce"
region = "us-east-1"
parameter_overrides = "Environment=staging"

[prod]
[prod.global.parameters]
stack_name = "prod-ecommerce-stack"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ecommerce"
region = "us-east-1"
parameter_overrides = "Environment=prod"
